server:
  port: 8081

spring:
  application:
    name: product-service

  datasource:
    url: jdbc:h2:file:~/data/productDB  # this specifies data will be stored in a file. not in memory
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
